"""AI intelligence report generation endpoints."""
from typing import Literal

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Request
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from ...shared.database import get_db

router = APIRouter()

REPORT_TYPES = Literal[
    "QUICK_SUMMARY",
    "FULL_INTELLIGENCE_DOSSIER",
    "FRAUD_INVESTIGATION_REPORT",
    "COMPLIANCE_CERTIFICATE",
    "BEHAVIORAL_ANOMALY_REPORT",
]


class IntelligenceSummaryRequest(BaseModel):
    identity_id: str = Field(..., min_length=5, max_length=50)
    report_type: REPORT_TYPES = "QUICK_SUMMARY"
    include_sections: list[str] = [
        "identity_overview", "risk_assessment",
        "institutional_history", "behavioral_notes"
    ]
    purpose_code: str = Field(..., min_length=4, max_length=50)
    language: str = Field(default="en", pattern="^(en|fr)$")
    format: Literal["json", "pdf"] = "json"


class InvestigationReportRequest(BaseModel):
    subject_identity_id: str = Field(..., min_length=5, max_length=50)
    investigation_reference: str = Field(..., min_length=5, max_length=100)
    investigating_officer: str = Field(..., min_length=3, max_length=50)
    include_network_map: bool = True
    network_depth: int = Field(default=2, ge=1, le=3)
    time_window_days: int = Field(default=365, ge=30, le=1825)
    purpose_code: str = Field(default="LAW_ENFORCEMENT_QUERY")
    legal_authority: Literal["COURT_ORDER", "STATUTORY_POWER", "CONSENT"] = "STATUTORY_POWER"
    court_order_reference: str | None = None


class ReportSection(BaseModel):
    summary: str
    confidence: str | None = None
    sources_verified: int | None = None


class IntelligenceReportResponse(BaseModel):
    request_id: str
    report_id: str
    identity_id: str
    report_type: str
    generated_at: str
    report: dict
    report_pdf_url: str | None = None
    report_expires_at: str | None = None
    audit_reference: str
    ai_model_used: str
    disclaimer: str


@router.post("/summary", response_model=IntelligenceReportResponse)
async def generate_intelligence_summary(
    request: Request,
    body: IntelligenceSummaryRequest,
    db: AsyncSession = Depends(get_db),
):
    """Generate an AI-powered intelligence summary report."""
    _require_intelligence_scope(request)

    from ...ai_intelligence_service.services.intelligence_engine import IntelligenceEngine

    engine = IntelligenceEngine(db)
    report = await engine.generate_summary(
        identity_id=body.identity_id,
        report_type=body.report_type,
        sections=body.include_sections,
        purpose_code=body.purpose_code,
        language=body.language,
        institution=request.state.institution,
    )

    import uuid
    from datetime import datetime, timedelta, timezone

    now = datetime.now(timezone.utc)
    report_id = str(uuid.uuid4())

    return IntelligenceReportResponse(
        request_id=request.state.request_id,
        report_id=report_id,
        identity_id=body.identity_id,
        report_type=body.report_type,
        generated_at=now.isoformat(),
        report=report.sections,
        report_pdf_url=f"https://api.idintel.com.gh/v1/reports/{report_id}/download" if body.format == "pdf" else None,
        report_expires_at=(now + timedelta(days=90)).isoformat(),
        audit_reference=str(uuid.uuid4()),
        ai_model_used=report.model_used,
        disclaimer=(
            "This report is generated by AI and is for authorized institutional use only. "
            "All decisions must include human judgment. IDIntel Ghana Ltd assumes no liability "
            "for decisions made solely on the basis of this report."
        ),
    )


@router.post("/investigation-report", response_model=IntelligenceReportResponse)
async def generate_investigation_report(
    request: Request,
    body: InvestigationReportRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
):
    """Generate a comprehensive investigation dossier for law enforcement / compliance."""
    # Law enforcement query requires appropriate institution type
    institution_type = request.state.institution.get("institution_type", "")
    if body.purpose_code == "LAW_ENFORCEMENT_QUERY" and institution_type not in (
        "LAW_ENFORCEMENT", "REGULATORY", "GOVERNMENT", "INTERNAL"
    ):
        raise HTTPException(
            403,
            "LAW_ENFORCEMENT_QUERY purpose code requires a law enforcement or regulatory institution.",
        )

    if body.legal_authority == "COURT_ORDER" and not body.court_order_reference:
        raise HTTPException(400, "court_order_reference is required when legal_authority is COURT_ORDER")

    _require_intelligence_scope(request)

    from ...ai_intelligence_service.services.intelligence_engine import IntelligenceEngine

    engine = IntelligenceEngine(db)
    report = await engine.generate_investigation_report(
        subject_identity_id=body.subject_identity_id,
        investigation_reference=body.investigation_reference,
        investigating_officer=body.investigating_officer,
        include_network_map=body.include_network_map,
        network_depth=body.network_depth,
        time_window_days=body.time_window_days,
        legal_authority=body.legal_authority,
        court_order_reference=body.court_order_reference,
        institution=request.state.institution,
    )

    import uuid
    from datetime import datetime, timedelta, timezone

    now = datetime.now(timezone.utc)
    report_id = str(uuid.uuid4())

    return IntelligenceReportResponse(
        request_id=request.state.request_id,
        report_id=report_id,
        identity_id=body.subject_identity_id,
        report_type="FRAUD_INVESTIGATION_REPORT",
        generated_at=now.isoformat(),
        report=report.sections,
        report_pdf_url=f"https://api.idintel.com.gh/v1/reports/{report_id}/download",
        report_expires_at=(now + timedelta(days=90)).isoformat(),
        audit_reference=str(uuid.uuid4()),
        ai_model_used=report.model_used,
        disclaimer=(
            "This intelligence dossier is classified RESTRICTED. Unauthorized disclosure is a "
            "criminal offence under the Computer Crimes Act 2008 (Act 722) of Ghana."
        ),
    )


@router.get("/reports/{report_id}/download")
async def download_report(
    request: Request,
    report_id: str,
):
    """Download a previously generated intelligence report as PDF."""
    _require_intelligence_scope(request)
    # In production: fetch pre-signed S3 URL for the report PDF
    raise HTTPException(501, "PDF generation not yet implemented in this version")


def _require_intelligence_scope(request: Request) -> None:
    role = getattr(request.state, "user_role", "")
    if role not in ("ANALYST", "COMPLIANCE_OFFICER", "INSTITUTION_ADMIN", "PLATFORM_ADMIN", "API_SERVICE"):
        raise HTTPException(403, "Insufficient role for intelligence report generation")
